@startuml
!pragma layout smetana
skinparam classAttributeIconSize 0

interface Kategorie <<protocol>>{
    +build_ui(): list[ft.Row]
    +extract(): list[ft.Row]
}

class StudiumKategorie
class HaushaltKategorie
class FreizeitKategorie

Kategorie <|.. StudiumKategorie
Kategorie <|.. HaushaltKategorie
Kategorie <|.. FreizeitKategorie

class StudiumKategorie {
    -modul: TextField
    -gruppenarbeit: RadioGroup

    +<<constructor>> __init__()
    +build_ui(): dict[str, Any]
    +extract(): dict[str, Any]
}

class HaushaltKategorie {
    -wiederkehrend: RadioGroup

    +<<constructor>>__init__()
    +build_ui(): list[ft.Row]
    +extract(): dict[str, Any]
}

class FreizeitKategorie {
    -hobby: TextField
    -ort: TextField

    +<<constructor>>__init__()
    +build_ui(): list[ft.Row]
    +extract(): dict[str, Any]
}

@enduml